version: "3"

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - node-network
    ports:
      - "8080:80"
  app:
    build:
      context: node
    container_name: app
    entrypoint: /usr/local/bin/dockerize -wait tcp://db:3306 -timeout 60s node index.js
    networks:
      - node-network
    volumes:
      - ./node:/usr/scr/app
    tty: true
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
